import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="mt-8 flex flex-col h-screen md:flex-row ">
					<div className="w-1/8 p-4 items-center grow flex flex-col bg-gray-100">
						<Link href="/" className="my-2 primaryButton">
							Home
						</Link>
						<Link href="/simpleServer" className="my-2 primaryButton">
							serverシンプル版
						</Link>
						<Link href="/simpleClient" className="my-2 primaryButton">
							cleintシンプル版
						</Link>
						<Link href="/client1" className="my-2 primaryButton">
							cleint1
						</Link>
						<Link href="/client2" className="my-2 primaryButton">
							cleint2
						</Link>
						<Link href="/playground" className="my-2 primaryButton">
							playground
						</Link>
					</div>
					<div className="ml-8 grow">{children}</div>
				</div>
			</body>
		</html>
	)
}
